version: '3.8'

services:

  # It's possible to put service proxy with its network (carousel_proxy) into a separate docker-compose file
  # (like in /docker/proxy/docker-compose.yml) and run it _before_ this main configuration. In that case one
  # should remove dependencies from service proxy from this configuration.
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  nginx:
    build:
      context: ./docker/nginx
      args:
        SITE_NAME: ${FRONTEND_HOST}
    environment:
      - VIRTUAL_HOST=${FRONTEND_HOST},${BACKEND_HOST}
    depends_on:
      - proxy
      - php
    volumes:
    - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
    - ./:/var/www/html/
    networks:
      - frontend
      - backend

  php:
    build:
      context: ./docker/php
    depends_on:
      - proxy
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html/
    networks:
      - backend

  mysql:
    image: mysql:8.0.23
    depends_on:
      - proxy
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file:
      - ./docker/env/${ENV}/mysql.env
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - proxy
    env_file:
      - ./docker/env/${ENV}/phpmyadmin.env
    environment:
      - VIRTUAL_HOST=phpmyadmin.${FRONTEND_HOST}
      - PMA_HOST=mysql
    networks:
      - frontend
      - backend


networks:
  proxy:
    driver: bridge
  frontend:
    external:
      name: carousel_proxy
  backend: